# Generated by Django 5.1.3 on 2025-01-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_photosmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photosmodel',
            name='tags',
        ),
    ]
