# Generated by Django 5.1.3 on 2025-01-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_photosmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='type_pic',
        ),
        migrations.RemoveField(
            model_name='work',
            name='type_pic',
        ),
        migrations.DeleteModel(
            name='food',
        ),
        migrations.DeleteModel(
            name='sports',
        ),
        migrations.DeleteModel(
            name='work',
        ),
    ]
