# Generated by Django 5.1 on 2025-01-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photograph',
            name='type_pic',
        ),
        migrations.DeleteModel(
            name='work',
        ),
        migrations.DeleteModel(
            name='photosModel',
        ),
    ]
